language: node_js
node_js:
  - "0.12"
  - "4.0"

before_script:
  - npm run lint
  - sleep 15
  - mongo test --eval 'db.addUser('travis', 'test')'

script:
  - npm run test-cov

sudo: false

notifications:
  email:
    - jed@keystonejs.com

services:
  - mongodb

git:
  depth:
    10

cache:
  directories:
    - node_modules
